name: Run Tests on Solutions Update

on:
  push:
    paths:
      - 'Solutions/**'
  pull_request:
    paths:
      - 'Solutions/**'

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup dependencies
        run: |
          sudo apt update
          sudo apt install -y gcc g++ openjdk-17-jdk python3

      - name: Detect language and run tests
        run: |
          # Detect what kind of solution file changed
          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -q '\.c$'; then
            echo "C detected"
            if [ -f Tests/test.c ]; then
              gcc Tests/test.c Solutions/*.c -o solution_c
              ./solution_c
            else
              echo "C test file not found."
            fi
          elif git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -q '\.cpp$'; then
            echo "C++ detected"
            if [ -f Tests/test.cpp ]; then
              g++ -I. Tests/test.cpp Solutions/*.cpp -o solution_cpp
              ./solution_cpp
            else
              echo "C++ test file not found."
            fi
          elif git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -q '\.py$'; then
            echo "Python detected"
            if [ -f Tests/test.py ]; then
              PYTHONPATH=Solutions python3 Tests/test.py
            else
              echo "Python test file not found."
            fi
          elif git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -q '\.java$'; then
            echo "Java detected"
            if [ -f Tests/test.java ]; then
              javac -d . Solutions/*.java Tests/*.java
              java test
            else
              echo "Java test file not found."
            fi
          else
            echo "No recognized language changes detected."
          fi
